SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SELECT * FROM producto;
SELECT nombre, precio AS precio_euros, ROUND(precio * 1.08, 2) AS precio_dolares FROM producto;
SELECT nombre AS 'nom de producto', precio AS 'euros', ROUND(precio * 1.08, 2) AS 'dòlars' FROM producto;
SELECT UPPER(nombre) AS 'Nombre en mayúscula', precio FROM producto;
SELECT LOWER(nombre) AS 'Nombre en minúscula', precio FROM producto;
SELECT nombre AS 'Nombre completo', UPPER(LEFT(nombre, 2)) AS 'Iniciales' FROM fabricante;
SELECT nombre, ROUND(precio) AS 'Precio redondeado' FROM producto;
SELECT nombre, TRUNCATE(precio, 0) AS 'Precio truncado' FROM producto;
SELECT codigo_fabricante FROM producto;
SELECT DISTINCT codigo_fabricante FROM producto;
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre, precio FROM producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 3, 2;
SELECT nombre, precio FROM producto ORDER BY precio ASC LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
SELECT * FROM producto WHERE codigo_fabricante = 2;
SELECT p.nombre AS nom_producte, p.precio AS preu, f.nombre AS nom_fabricador FROM producto AS p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo;
SELECT p.nombre AS nom_producte, p.precio AS preu, f.nombre AS nom_fabricador FROM producto AS p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo ORDER BY f.nombre;
SELECT p.codigo AS codi_producte, p.nombre AS nom_producte, f.codigo AS codi_fabricador, f.nombre AS nom_fabricador FROM producto AS p INNER JOIN fabricante AS f;
SELECT p.nombre AS nom_producte, p.precio AS preu_producte, f.nombre AS nom_fabricador FROM producto AS p INNER JOIN fabricante AS f ORDER BY p.precio ASC LIMIT 1;
SELECT p.nombre AS nom_producte, p.precio AS preu_producte, f.nombre AS nom_fabricador FROM producto AS p INNER JOIN fabricante AS f ORDER BY p.precio DESC LIMIT 1;
SELECT * FROM producto AS p INNER JOIN fabricante AS f WHERE f.nombre = 'Lenovo';
SELECT * FROM producto AS p INNER JOIN fabricante AS f WHERE f.nombre = 'Crucial' AND p.precio > 200;
SELECT * FROM producto AS p INNER JOIN fabricante AS f WHERE f.nombre = 'Asus' OR f.nombre = 'Hewlett-Packard' OR f.nombre = 'Seagate';
SELECT * FROM producto AS p INNER JOIN fabricante AS f WHERE f.nombre IN ('Asus', 'Hewlett-Packard', 'Seagate');
SELECT p.nombre AS nom_producte, p.precio AS preu_producte, f.nombre AS nom_fab FROM producto AS p JOIN fabricante AS f WHERE f.nombre LIKE '%e';
SELECT p.nombre AS nom_producte, p.precio AS preu_producte, f.nombre AS nom_fab FROM producto AS p JOIN fabricante AS f WHERE f.nombre LIKE '%w%';
SELECT p.nombre AS nom_producte, p.precio AS preu_producte, f.nombre AS nom_fab FROM producto AS p JOIN fabricante AS f WHERE p.precio >= 180 ORDER BY p.precio DESC, p.nombre ASC;
SELECT f.codigo AS codi_fabricador, f.nombre AS nom_fabricador FROM fabricante AS f JOIN producto AS p WHERE p.codigo_fabricante IS NOT NULL;
SELECT apellido1, apellido2, nombre FROM persona WHERE tipo = 'alumno' ORDER BY apellido1, apellido2, nombre;
SELECT apellido1, apellido2, nombre FROM persona WHERE tipo = 'alumno' AND telefono IS NULL;
SELECT * FROM persona WHERE tipo = 'alumno' AND YEAR(fecha_nacimiento) = 1999;
SELECT * FROM persona WHERE tipo = 'profesor' AND telefono IS NULL AND nif LIKE '%K';
SELECT * FROM asignatura WHERE cuatrimestre = 1 AND curso = 3 AND id_grado = 7;
SELECT p.apellido1 AS primer_cognom, p.apellido2 AS segon_cognom, p.nombre AS nom, d.nombre AS departament FROM profesor pr JOIN persona p ON p.id = pr.id_profesor JOIN departamento d ON d.id = pr.id_departamento ORDER BY p.apellido1 ASC, p.apellido2 ASC, p.nombre ASC;
SELECT a.nombre AS assignatura, ce.anyo_inicio AS any_inici, ce.anyo_fin AS any_fi FROM alumno_se_matricula_asignatura ama JOIN persona p ON p.id = ama.id_alumno JOIN asignatura a ON a.id = ama.id_asignatura JOIN curso_escolar ce ON ce.id = ama.id_curso_escolar WHERE p.nif = '26902806M';
SELECT DISTINCT d.nombre AS departament FROM departamento d JOIN profesor pr ON pr.id_departamento = d.id JOIN asignatura a ON a.id_profesor = pr.id_profesor JOIN grado g ON g.id = a.id_grado WHERE g.nombre = 'Grado en Ingeniería Informática (Plan 2015)';
SELECT DISTINCT p.nombre AS nom, p.apellido1 AS primer_cognom, p.apellido2 AS segon_cognom FROM persona p JOIN alumno_se_matricula_asignatura ama ON p.id = ama.id_alumno JOIN curso_escolar ce ON ce.id = ama.id_curso_escolar WHERE ce.anyo_inicio = 2018 AND ce.anyo_fin = 2019;
SELECT d.nombre AS nombre_departamento, pe.apellido1 AS primer_cognom, pe.apellido2 AS segon_cognom, pe.nombre AS nombre_profesor FROM persona AS pe LEFT JOIN profesor AS pr ON pr.id_profesor = pe.id LEFT JOIN departamento AS d ON d.id = pr.id_departamento WHERE pe.tipo = 'profesor' ORDER BY (d.nombre IS NULL) ASC, d.nombre ASC, pe.apellido1 ASC, pe.apellido2 ASC, pe.nombre ASC;
SELECT pe.apellido1 AS primer_cognom, pe.apellido2 AS segon_cognom, pe.nombre AS nom_professor FROM persona AS pe LEFT JOIN profesor AS pr ON pr.id_profesor = pe.id WHERE pe.tipo = 'profesor' AND pr.id_profesor IS NULL ORDER BY pe.apellido1, pe.apellido2, pe.nombre;
SELECT d.nombre AS nom_departament FROM departamento AS d LEFT JOIN profesor AS p ON p.id_departamento = d.id WHERE p.id_profesor IS NULL ORDER BY d.nombre;
SELECT pe.apellido1 AS primer_cognom, pe.apellido2 AS segon_cognom, pe.nombre AS nom_professor FROM persona AS pe INNER JOIN profesor AS pr ON pr.id_profesor = pe.id LEFT JOIN asignatura AS a ON a.id_profesor = pr.id_profesor WHERE a.id_profesor IS NULL ORDER BY pe.apellido1, pe.apellido2, pe.nombre;
SELECT a.nombre AS nom_assignatura FROM asignatura AS a LEFT JOIN profesor AS p ON a.id_profesor = p.id_profesor WHERE p.id_profesor IS NULL ORDER BY a.nombre;
SELECT d.nombre AS nom_departament FROM asignatura AS a RIGHT JOIN profesor AS p ON a.id_profesor = p.id_profesor RIGHT JOIN departamento AS d ON p.id_departamento = d.id WHERE a.id IS NULL ORDER BY d.nombre;
SELECT COUNT(id) FROM persona WHERE tipo = 'alumno';
SELECT COUNT(id) FROM persona WHERE tipo = 'alumno' AND YEAR(fecha_nacimiento) = 1999;
SELECT d.nombre AS nom_departament, COUNT(p.id_profesor) AS num_professors FROM departamento AS d INNER JOIN profesor AS p ON p.id_departamento = d.id GROUP BY d.nombre ORDER BY num_professors DESC;
SELECT d.nombre AS nom_departament, COUNT(p.id_profesor) AS num_professors FROM departamento AS d LEFT JOIN profesor AS p ON p.id_departamento = d.id GROUP BY d.nombre ORDER BY d.nombre;
SELECT g.nombre AS nom_grau, COUNT(a.id) AS num_assignatures FROM grado AS g LEFT JOIN asignatura AS a ON a.id_grado = g.id GROUP BY g.nombre ORDER BY num_assignatures DESC;
SELECT g.nombre AS nom_grau, COUNT(a.id) AS num_assignatures FROM grado AS g LEFT JOIN asignatura AS a ON a.id_grado = g.id GROUP BY g.nombre HAVING COUNT(a.id) > 40 ORDER BY num_assignatures DESC;
SELECT g.nombre AS nom_grau, a.tipo AS tipus_assignatura, SUM(a.creditos) AS total_credits FROM grado AS g INNER JOIN asignatura AS a ON a.id_grado = g.id GROUP BY g.nombre, a.tipo ORDER BY g.nombre, a.tipo;
